name: mypy
description: Check typing using Mypy

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: lvieirajr/eventide/.github/actions/uv@test-actions
    - name: Mypy
      run: make mypy
      shell: bash
