name: "uv"
description: "Set up uv and all the dependencies"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: lvieirajr/eventide/.github/actions/uv@test-actions
    - name: Ruff linter
      run: ruff check --output-format=github ./
      shell: bash
    - name: Ruff formatter
      run: ruff format --check --diff ./
      shell: bash
