name: "uv"
description: "Set up uv and all the dependencies"

inputs:
  python-version:
    description: "Python version"
    required: false

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v5
      if: ${{ ! inputs.python-version }}
      with:
        enable-cache: true
        prune-cache: true
        cache-dependency-glob: |
          **/uv.lock
          **/pyproject.toml
    - uses: astral-sh/setup-uv@v5
      if: ${{ inputs.python-version }}
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: true
        prune-cache: true
        cache-dependency-glob: |
          **/uv.lock
          **/pyproject.toml
    - name: Install dependencies
      run: uv sync --all-extras --frozen --no-install-project
      shell: bash
