name: "ci"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  UV_COMPILE_BYTECODE: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          prune-cache: true
          cache-dependency-glob: |
            **/uv.lock
            **/pyproject.toml
      - name: Install dependencies
        run: uv sync --all-extras --frozen --no-install-project
      - name: Ruff linter
        run: ruff check --output-format=github
      - name: Ruff formatter
        run: ruff format --check --diff
