name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  UV_COMPILE_BYTECODE: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: lvieirajr/eventide/.github/actions/ruff@test-actions

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lvieirajr/eventide/.github/actions/uv@test-actions
      - name: Mypy
        run: mypy ./

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    steps:
      - uses: actions/checkout@v4
      - uses: lvieirajr/eventide/.github/actions/uv@test-actions
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pytest
        run: pytest ./
